export const FETCH_ACADEMY_DATA = "FETCH_ACADEMY_DATA"
export const GET_ACADEMY_DATA = "GET_ACADEMY_DATA"

export const FETCH_GAMESQUARE_DATA = "FETCH_GAMESQUARE_DATA"
export const GET_GAMESQUARE_DATA = "GET_GAMESQUARE_DATA"

export const FETCH_AB_DATA = "FETCH_AB_DATA"
export const GET_AB_DATA = "GET_AB_DATA"